export const loginDB = [
  // Students
  {
    id: 1,
    username: "student01",
    password: "password123",
    role: "student",
    name: "John Doe",
    mobileNumber: "0712345678",
    email: "johndoe@student.com",
    userDetails: "A third-year student specializing in Computer Science.",
  },
  {
    id: 2,
    username: "student02",
    password: "studentPass2024",
    role: "student",
    name: "Jane Smith",
    mobileNumber: "0712345679",
    email: "janesmith@student.com",
    userDetails: "A second-year student in the Information Technology department.",
  },
  {
    id: 3,
    username: "student03",
    password: "myStudentPass01",
    role: "student",
    name: "Michael Brown",
    mobileNumber: "0712345680",
    email: "michaelbrown@student.com",
    userDetails: "A first-year student passionate about programming and AI.",
  },
  {
    id: 4,
    username: "student04",
    password: "s1234pass",
    role: "student",
    name: "Emily Davis",
    mobileNumber: "0712345681",
    email: "emilydavis@student.com",
    userDetails: "A final-year student with a focus on Data Science.",
  },
  {
    id: 5,
    username: "student05",
    password: "secureStudent567",
    role: "student",
    name: "William Taylor",
    mobileNumber: "0712345682",
    email: "williamtaylor@student.com",
    userDetails: "A second-year student majoring in Software Engineering.",
  },

  // Faculty (Lecturers)
  {
    id: 6,
    username: "faculty01",
    password: "securepass456",
    role: "faculty",
    name: "Dr. Sarah Green",
    mobileNumber: "0712345683",
    email: "sarah.green@faculty.com",
    userDetails: "Lecturer in Computer Science, specializing in Machine Learning.",
  },
  {
    id: 7,
    username: "faculty02",
    password: "lecturePass789",
    role: "faculty",
    name: "Prof. David White",
    mobileNumber: "0712345684",
    email: "david.white@faculty.com",
    userDetails: "Professor of Mathematics, focusing on algorithms and cryptography.",
  },
  {
    id: 8,
    username: "faculty03",
    password: "facultyPass2024",
    role: "faculty",
    name: "Dr. Olivia Black",
    mobileNumber: "0712345685",
    email: "olivia.black@faculty.com",
    userDetails: "Lecturer in Software Engineering, with expertise in web development.",
  },
  {
    id: 9,
    username: "faculty04",
    password: "teachLecturer01",
    role: "faculty",
    name: "Dr. Richard Harris",
    mobileNumber: "0712345686",
    email: "richard.harris@faculty.com",
    userDetails: "Lecturer in Computer Networks and Cloud Computing.",
  },
  {
    id: 10,
    username: "faculty05",
    password: "professorPass112",
    role: "faculty",
    name: "Prof. Linda Martinez",
    mobileNumber: "0712345687",
    email: "linda.martinez@faculty.com",
    userDetails: "Professor of AI and Data Science, focusing on neural networks.",
  },

  // Admins
  {
    id: 11,
    username: "admin01",
    password: "admin@1234",
    role: "admin",
    name: "Alice Walker",
    mobileNumber: "0712345688",
    email: "alice.walker@admin.com",
    userDetails: "System administrator, managing user accounts and system security.",
  },
  {
    id: 12,
    username: "admin02",
    password: "adminSecure2024",
    role: "admin",
    name: "Bob Johnson",
    mobileNumber: "0712345689",
    email: "bob.johnson@admin.com",
    userDetails: "Administrator in charge of maintaining system infrastructure and services.",
  },
];
